    
                                 
    
                              
   
                                       
    

  
                                                                          
                                                                    
                                                                      
               
   
                 
                                                                       
              
                                                                           
                                                                           
             
   

  
                                                                          
                                                                          
                                                        
                                                                           
                                                                          
                                                                         
                                                                       
                                                                          
                                                                         
                                                                      
                                                                         
                                                                      
                                                                          
                                                       
  
                                                                       
                     
  
                    
                                 
   

#undef USE_COMPILER
#undef RELY_ON_LOADSEG_DETECTION

  
                                                                           
                                                                      
                                                                             
                                                                     
             
                                                                           
                                                                         
                                                                            
                                                                          
                                                           
                                                                             
                              
   

                                                                            
                                            
                                                                        
                                                            
                                                   
   

  
                                                            
                                
   

  
                                                                               
          
                             
   

#define MUSIC_VOLUME 80
